name: Core
version: '1.0'
main: org.core.Core
api-version: '1.21'
commands:
  core:
    description: "core"
    usage: "/core"
  coreclear:
    description: "coreclear"
    usage: "/coreclear"
  corecheck:
    description: "coreclear"
    usage: "/coreclear"
  corelevelreset:
    description: "coreLevelReset"
    usage: "/coreLevelReset"

  gc:
    description: "gc"
    usage: "/gc"
